name: Main

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 'Run lint'
        run: ./gradlew detekt lintDebug

      - name: 'Run local tests'
        run: ./gradlew testDebug

      - name: 'Assemble test artifacts'
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - name: 'Decode Firebase Service Account JSON'
        run: echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE_64 }} | base64 -d > service_account.json

      - name: 'Run device tests on Firebase Test Lab'
        run: |
          gcloud auth login --cred-file=service_account.json
          gcloud config set project cars-17543
          gcloud firebase test android run \
          --app app/build/outputs/apk/debug/app-debug.apk \
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --device version=34,orientation=portrait,model=MediumPhone.arm,locale=en_US \